version: '3.8'

services:
  gemini-antiblock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Gemini API 基础 URL
      - UPSTREAM_URL_BASE=https://generativelanguage.googleapis.com
      
      # 最大连续重试次数
      - MAX_CONSECUTIVE_RETRIES=100
      
      # 启用调试模式
      - DEBUG_MODE=true
      
      # 重试延迟（毫秒）
      - RETRY_DELAY_MS=750
      
      # 重试后是否过滤思考内容
      - SWALLOW_THOUGHTS_AFTER_RETRY=true
      
      # 服务器端口
      - PORT=8080
      
      # 如果你有 Gemini API Key，可以在这里设置
      # - GEMINI_API_KEY=your_api_key_here
    
    # 可选：挂载配置文件
    # volumes:
    #   - ./.env:/app/.env:ro
    
    # 健康检查
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 重启策略
    restart: unless-stopped
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
